name: lint.yml

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          cache: 'true'
          dotnet-version: '8.0.x'
      - name: Formata o arquivo
        run: dotnet format 